apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-ng
  template:
    metadata:
      labels:
        app: syslog-ng
    spec:
      containers:
      - name: syslog-ng
        image: balabit/syslog-ng:latest
        ports:
        - containerPort: 514
          name: syslog
        volumeMounts:
        - name: syslog-ng-config
          mountPath: /etc/syslog-ng/syslog-ng.conf
          subPath: syslog-ng.conf
      volumes:
      - name: syslog-ng-config
        configMap:
          name: syslog-ng-config
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-ng-service
spec:
  ports:
  - port: 514
    targetPort: syslog
  selector:
    app: syslog-ng
